publicationPath: "var/rrdp_contents"
rrdpURI: "http://rrdp:8080"
rsyncMirroring: ["rsync://rpki.apnic.net/repository", "rsync://rpki.apnic.net/member_repository"]
rsyncPath: "var/rsync"
rsyncUpdateFrequency: 60
rrdpPort: 8080