publicationPath: "/home/rcintra/temp/rpki_contents"
rrdpURI: "http://localhost:8080"
rsyncMirroring: ["rsync://rpki.apnic.net/repository", "rsync://rpki.apnic.net/member_repository"]
rsyncPath: "/home/rcintra/temp/rsync_test"
rsyncUpdateFrequency: 60
rrdpPort: 8080